#!/bin/bash

cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
. build/envsetup.sh
lunch qssi
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G
ccache -o compression=true
ccache -z

# stuffs
up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	make api-stubs-docs
	make system-api-stubs-docs
	make test-api-stubs-docs
}

make_rom(){
                WITHOUT_CHECK_API=true make -j14 systemimage
		zip=$(up out/target/product/generic_arm64/*img)
		echo " "
		echo "$zip"
}
make_metalava
make_rom
