#!/bin/bash

cd /tmp/rom # Depends on where source got synced
rm -rf .repo & # lets remove unnecessary things, so that no storage issue can occur

# Normal build steps
. build/envsetup.sh
lunch lavender
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 50G
ccache -o compression=true
ccache -z
#make api-stubs-docs || echo no problem, we need ccache
#make hiddenapi-lists-docs || echo no problem, we need ccache
#make system-api-stubs-docs || echo no problem we need ccache
#make test-api-stubs-docs || echo no problem, we need ccache
#WITHOUT_CHECK_API=true make -j8 systemimage &
#sleep 60m
#kill %1
#ccache -s

 stuffs
up(){
	curl --upload-file $1 https://transfer.sh/
}

make_metalava(){
	make api-stubs-docs
	make system-api-stubs-docs
	make test-api-stubs-docs
}

make_rom(){
                make -j8
		zip=$(up out/target/product/lavender/*zip)
		echo " "
		echo "$zip"
}
make_metalava
make_rom
