#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://transfer.sh/k0N5x/ccache.tar.gz
wget https://transfer.sh/k0N5x/ccache.tar.gz
aria2c https://transfer.sh/k0N5x/ccache.tar.gz

cd /tmp # Where to download cccahe
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50
time tar xf ccache.tar.gz
find ccache.tar.gz -delete
