#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://server.nippon.workers.dev/ccache/nippa/ccache.crdroid.tar.gz

cd /tmp # Where to download cccahe
sudo apt install wget -y

wget https://server.nippon.workers.dev/ccache/nippa/ccache.tar.gz -O a.tar.gz
echo "Downloaded!"

time tar xf a.tar.gz
echo "Extracted!"
find a.tar.gz -delete
