#!/bin/bash
# Lets see machine specifications and environments
df -h
free -h
nproc
cat /etc/os*
env

url=https://server.nippon.workers.dev/ccache/nippa/ccache.crdroid.tar.gz

cd /tmp # Where to download cccahe
aria2c https://server.nippon.workers.dev/ccache/nippa/ccache.tar.gz
echo "Downloaded!"
wget https://server.nippon.workers.dev/ccache/nippa/ccache.tar.gz

time wget $url || time wget $url
time aria2c $url -x16 -s50 || time aria2c $url -x16 -s50

time tar xf ccache.tar.gz
echo "Extracted!"
find ccache.tar.gz -delete
