#!/bin/bash

MANIFEST=...
BRANCH=lineage-18.1

#cd /tmp
#sudo apt install wget
#wget https://gdmbd.sasohan.workers.dev/ccache.tar.gz
#tar xf ccache.tar.gz
#rm -rf ccache.tar.gz
#ls ccache
#echo "Done"
mkdir -p /tmp/rom
#mkdir -p ~/bin
#PATH=~/bin:$PATH
#curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
#chmod a+x ~/bin/repo
#gpg --recv-key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
#curl https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ~/bin/repo
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
git config --global user.name nnippon
git config --global user.email adameyyad999@gmail.com
#repo init --depth=1 -u "$MANIFEST" -b "$BRANCH"
repo init --depth=1 --no-repo-verify -u https://source.codeaurora.org/quic/la/la/system/manifest/ -b release -m LA.QSSI.11.0.r1-12400.02-qssi.0.xml -g default,-device,-mips,-darwin,-notdefault
#--depth=1
# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8:(
#repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc --all)
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8 
#|| repo sync -c --force-sync --no-tags --no-clone-bundle -j8
#git clone https://github.com/TasinAyon/device_xiaomi_lavender --depth=1 copy/test
#cp ./copy/test/go_defaults_commontest.mk ./build/target/product
#echo '$(call inherit-product, $(SRC_TARGET_DIR)/product/go_defaults_commontest.mk)' >> ./build/target/product/gsi_arm64.mk
#git clone https://github.com/TasinAyon/device_xiaomi_sdm660-common --depth=1 -b dumaloo-release device/xiaomi/sdm660-common
#git clone https://github.com/TasinAyon/kernel_xiaomi_lavender --depth=1 -b dumaloo-release kernel/xiaomi/sdm660
#git clone https://github.com/TasinAyon/vendor_xiaomi_lavender --depth=1 -b dumaloo-release vendor/xiaomi/lavender
#git clone https://github.com/TasinAyon/vendor_xiaomi_sdm660-common --depth=1 -b dumaloo-release vendor/xiaomi/sdm660-common
#git clone https://github.com/TasinAyon/device_xiaomi_lavender-1 --depth=1 -b dumaloo-release device/xiaomi/lavender
#git clone https://github.com/TasinAyon/android_device_qcom_sepolicy --depth=1 -b lineage-18.1-legacy-um device/qcom/sepolicy-legacy-um
#echo 'PRODUCT_PACKAGES += \
    #ThemePicker \' >> ./build/target/product/gsi_arm64.mk
#rm -rf ./hardware/qcom/gps

