#!/bin/bash

MANIFEST=https://github.com/XOSP-Reborn/manifest
BRANCH=eleven

#cd /tmp
#sudo apt install wget
#wget https://gdmbd.sasohan.workers.dev/ccache.tar.gz
#tar xf ccache.tar.gz
#rm -rf ccache.tar.gz
#ls ccache
#echo "Done"
mkdir -p /tmp/rom
#mkdir -p ~/bin
#PATH=~/bin:$PATH
#curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
#chmod a+x ~/bin/repo
#gpg --recv-key 8BB9AD793E8E6153AF0F9A4416530D5E920F5C65
#curl https://storage.googleapis.com/git-repo-downloads/repo.asc | gpg --verify - ~/bin/repo
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
git config --global user.name nnippon
git config --global user.email adameyyad999@gmail.com
repo init --depth=1 -u "$MANIFEST" -b "$BRANCH"

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8:
repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc --all) || repo sync -c --force-sync --no-tags --no-clone-bundle -j8
#git clone https://github.com/TasinAyon/device_xiaomi_lavender --depth=1 copy/test
#cp ./copy/test/go_defaults_commontest.mk ./build/target/product
#echo '$(call inherit-product, $(SRC_TARGET_DIR)/product/go_defaults_commontest.mk)' >> ./build/target/product/gsi_arm64.mk
